### ISSUE TITLE
Ratings preview

### ISSUE THREAD

**Issue by randomtomx** [tennisonchan/youtube-preview#29]
You're probably aware of this, but the ratings preview doesn't work atm.

Browser: Chrome

**Comment by iiiGerardoiii** [comment]
It doesn't work here either, did you find a fix?

**Comment by randomtomx** [comment]
I switched to https://chrome.google.com/webstore/detail/ratings-preview-for-youtu/cgbhdenfmgbagncdmgbholejjpmmiank

**Comment by iiiGerardoiii** [comment]
Wait, so is this repo no longer maintained? Is there a public repo of the one you just liked?
