### ISSUE TITLE
can't download chrome site

### ISSUE THREAD

**Issue by oddukgi** [tennisonchan/youtube-preview#5]

**Comment by cristianoliveira** [comment]
:+1:

Correct link should be: 
https://chrome.google.com/webstore/detail/video-preview/hmggjocpafbpjdhoknaneokaklekakeh

**Comment by tennisonchan** [comment]
Thanks @darongE and @cristianoliveira. I re-uploaded to my new account and have updated the link to chrome store. Thanks!
